language: go
go:
- 1.12.x
before_install:
- curl -fsSL https://get.pulumi.com/ | sh
- export PATH=$PATH:$HOME/.pulumi/bin
script:
- make prepare-aws-pulumi
- make deploy-aws-pulumi; export PULUMI_RESULT=$?
- make cleanup-aws-pulumi
- exit $PULUMI_RESULT
env:
  global:
  - secure: wlH2uabnKoIjVULGCnl6brAQ4p8ZJEiVaJ0abkBG8LtnUyeIQ4wyETVyWigjweTXxZIPAAClcIIXCoU4JbRnDU9N/sLVcYQia5PAMplC2k41ZWkPGVdd07L+m8FL7VFADizNhjVI/VrRrlDG8Po0ODpQjoQALp0YsOlpaAhXFoRhQo1t+JugqLkuezWn8lUwmhhbgyYfnH+lQhbgfjM+aD+NarJsn7n199oVtn5k8+PY/W8U4L2ludsgPnd6NcpvrfVjor6pgaMF0fg5IJRXiq2W1P80ySjNxUvSev2Gm1T15Nc+iz47FuK6E3XktE/EOXgapNLl2ST0jNqiYPyp/OTpeOJXYBtDTuJbyWzBRQnWYjofpHWsjig5Bg3Tj1hbDZLacUu6QeeP3ZD5oV20ShWYyrwco3mBbcaRLw7PB0/uz4TQSeFoFZ78Zeu5Afh4QpqhZYbRkNsdj+qLhXIOSPt7lyfb3SGA3ZRiQtCSR1JFQB2BSQjwCGo1lMFdDEV89qCQuOmnvGFxSeb9LkpELDlzUUrUQGlTanL6kIcfOQ8PAUFlde7rAMt5h+xtnaX4MDsnQBBKVcbFAH2JxMvyi4YGUJK6zIvAB27RC6WqTaM+IHCNrlDb3AY5p/CDc6Yp0hD3M1cH/mPZAE6YuqwsWklM9z4la+i//WYmKZh9tlw=
  - secure: RC5ZmEfxvo6UAcSQDO+FsZUDOtX1QYa3sdeON8Iq5Mq2IZeJoSy7MX7yMHCaC++hD2MZroOAEA9aRI5CH2yh9FPeoN1nQrwkNnN0dWDGWdUuDdQlZD3Z87R2hIyDj+HaPPO4nU5XLQ38ZzVYnVbXuzs7wlA5h9LBlCo4gL9OX0Y1xix3PpslKqN3Sgek+74REfiu/yBRUbhsZP3HMh4f9aiB2bqmsnAw+MOHI+9OAiArOTVmhxEqTh1uX00F0rGmCdz2VTnkJsu0mO3zY/CnK3gxll4tTkinD1IAGmnoKNrRIYGIx3xB2R0vkrGMBTDTGPXgnp4BjwjgOCtd8RqRudC1aot3BQMKypNe1vY8lwZu75/JahCJY3xxhlIZFX0oIHaz67k7vdOVduurn4cgKaJFyFe8F35OSTqxhZOxGlAaFDqBX4osiwkeYNeHWkx2i4K8BfYX9aXj0MCLkgy6CGgznY6h74usyUsmg+YOCY/X6U+UilhTuY4L7nMs3DFpv90mcAt4yNiPtPfGWxH4Pd0yKebR6YlH1EzRCYa7gdLqtTjIUWonK3aB/vmH+IM5aiIfo8a4KMYm1SDPQ1yj3DAWtF0F0j2/S3ovfyHME2xUfovkaJkSZN2qNeeEceVnli2VeTt9CKvHklWAr+jX+16vqQIlV2+wjT1iAV0ygQA=
