language: go
os: linux
arch: arm64-graviton2

sudo: required

addons:
  apt:
    update: true

go:
  - 1.14.x

env:
  global:
    - GO111MODULE=off
    - secure: "Fncxoe3JfB2CbD+a9zcR/wJdjdIEofqv7euG8yR+iDN7OATfLZZEoZ3LtmeOj224B7B+oi6/UwcUwo7GmeUP2iRHwAwjYZDgT8Am15OitDjeAL/PNaL9GFyR13T+33AaAvN4i3xHGBA93kw6p3XcmKnGtqt+j9ufKRdYZDZnXh5kqjRcsnVZH858uBIu8yOZ9KI2lPOxmp650wMLCwCXurMhg/CT9vjHCpUhGGqHf+yMaxGvIuWdj+8s7A1jH1NpcdNGDoTbcDCME8Ptl/xx4SOQKAs+28SB5R65EBAX0Gy7bIqECwg28ozBUsVJaTDgh/uOUpeZNLOOe5Qe2K9nsxYROP6dzr7uHsy8nyIfuPxBdr8Ekjg32eNDDxdmhDGt6ATcfFRT2ies+y4n8du7NkNEPaYZomBpxJ4TbNjDKzjHbFRYHmSKWi26WPuyAucD0BEQIuTAy9ZpLgdHSZMkfnQY+27bG7udya+qYAfjLBbSfuC6PvWMB36Kxb79/p/L8c1wUqxkeiQ1T/YGSVPUQUIGlJTG8Ap7aTc8wyZAipmkStj54xSpPMDExS6RdWmjpnmNof+VBKIkFJy8TfW/ZUQeQyu7bZ+cZHwiiGIDjXY544Ly7qLr3CUeEJWT+OUu0LTZsjquSZGc7AIxd46qGq+9KcapngKNYp8lVHb+VSM="
    - secure: "wni4O6FVTmAE1j8ddg9YGwOn4KU1OVnQFlzFPSXcjNVTAhhXp9p6lNcTVmzphVnx1crDbpltE8ENc+aHH8p6o05vWOrJYM2Tc2RyY5DJWGnM4hzcIIRKuxahYuHQMOTDksN7aFVzrlaUm2kGRvb/MJ851hcmFok7UtAPozOlzAz9c//Y8ttgqlP2LARhJiV5iYOij4ic4T/Ebd5TQAUPSwCWE4dSEPpNR1qnmHI/PrbUfUMS6oJVKEmIct4RDHYgl1j3UEMFwNhtlrxU8r8z4HfRXHZs40oBtLPdXke2AJywl7A/rU/jFX6e1safew0juLdC/AzcWvmmLx7S89vh1Y8wMt/Wn9ULfN7+jAWMdbJbwV38Y/Ok5uwFiL39ELQYUQCJv5Vabuf59GHQIf3hCEl9SXD3hI8DiTjWV7hRgIzWd12IYjx43xOBbHit8BSr6GgIHepEB8aNTUjdecR+bgfpBqnkTBfO6V2GOMZrYMGgi1MymtGgZUhTX3IfdsszBlGALLEFpG9OMvI7U2uOaJjM9fmkOfoogVS3xEevcTJwJbUk9I4ZgKjt5J44xiKHRERhQyt8de/USQTf/pHNE+nG0clRC02EY7j7UL8tzGoqn19Jo8WKdCC1PeQY6Yhewf0OcZfH+Qr7hgOdc6OIq8GQq6qq6OWnD7EF6vjK008="

before_install:
  - curl -fsSL https://get.pulumi.com/ | sh
  - export PATH=$PATH:$HOME/.pulumi/bin
  - pulumi version
  - sudo apt-get -y install pwgen #used in Makefile to generate the random admin password

script:
  - export STACK_SUFFIX="-$(pwgen -s 8 1)"
  - export ADMIN_PASSWORD=$(pwgen -s 16 1)
  - export SEED_JOB_GROOVY_FILE=jenkins/pipeline-configure.groovy
  - make deploy test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    make jenkins-aws; fi

after_script:
  - make cleanup
