language: go
os: linux
arch: arm64-graviton2

sudo: required

addons:
  apt:
    update: true

go:
  - 1.14.x

env:
  global:
    - GO111MODULE=off
    - secure: "DBzL6KIj5SI4QmuoOpB+/gx0VI13JbRjTSTMcFznvm660Y5uZpFDSPbGWXPhuFmEtila3WfOvJBMN4stpQGQUkvqhm27stvHKwLevR6eRsJPiqUzdn6JYuJSflnjI/5j8396snSTgjaoJ6FnG6HwCxTWkAmFxysWo6GHyz66g141We/T+sCb1y1fsg7UWbR3VBpoNGvIgqTnFasJho2OBWKOVQ/olLq7nW4ea1tGyGG3gwbx7h0ee2tZEhDAbyNrnoF3HSJULMiVqJK0E4KfDifTyBGojyCc7ut6A7D2rG8SNL1FKaBpgNBFVAsNXWH1HbEjzSYHUjq0H0LJrNHGG5rVSLnDd3HY12P5kaGBvfupBOPzXL5tExOK6ZSJcx6BxPCElzdkutERzXDW2xIhLvLdrTTMmEH4owerbqEDpT5ELNZKJmTnTXDuGCmqlRIp6Pi4s0Hu3zO35iX3BIWztP1dyA57kYr3wR6gqjAz/rmYQ4F3bvCtHN1sMpNOnaTCr6mmRs27GfDkrYqMK5j4S+MqxZ1FxGqsFeEKILsDtPMDqpxqjMKp5XZMKNvFfhblHb9hfaAkXG4xhRaLfbU8yzozhz5CFwm5d7ziHPG2pSgPnEEf7+ZQKvorhTPQIkz9anRv2uJW1UX7hSoxocoXQxOxK0KxoHaEo0BA8Ada+mM="
    - secure: "jj/b0jv7zkpOnp83RSaWiCac4LXYQQdx1r9DRRAf1TBAB4EecGP/be71y4TJrQ0QhEmEAOHzymsW1QMSHVyUHRbpoBge0vY0F+vKLzfCTdDw3WxDgSB1OEW7bQXHBftCqoSmRo8LwtmYxfu/8nexX5OBcx4NXoLn1XMbg7CIbZVUsI3yZpQ/Kw9d7rSr1+/MbzPcFcDsBPNUM6BRBBu7VP/Hbw9VBoTgnojPKrEdcCaVCJ6RbJfD03fs4Ep4sbL0zpx5Usb90L0B8CTUMoeDa3hb4NOXPV8Uy3HUct/7O/kAUxdx2M/Kq6Qfw9Vq+91KojZeHNgPaH62603h5yOil85R+h1k8PjGmjTtvm7KhhlyzJfT9Ghoz7iWqM0a4egGJmgMGuvSN5GOzFtZGd1y+hoLV6B8DNc2HvXUAmUssgFee5pBpBFnGoIPxbqlQbCZkvk2LgiKKG0XLNAeGM5Vqt0wkZoi8z18ZriS9PTsGW7X43D3kC1Yfi8Zc5KuxTqNd68xpKjHBXvMzo9ibWtlTaspDFIuFr8a1nLy/pfGqYUHwid7r5YO2nAahP3vvuqJNR5XqK2C5dLFwd3vVt0F2o1hWKkUQMSqrYM/UKLWotju9P1oko9Asfr860Oi3oWkn0Apg7gja91dinGZ7040I0q0cBhapPgsTP+UOdmfnCA="

before_install:
  - curl -fsSL https://get.pulumi.com/ | sh
  - export PATH=$PATH:$HOME/.pulumi/bin
  - pulumi version
  - sudo apt-get -y install pwgen #used in Makefile to generate the random admin password

script:
  - export STACK_SUFFIX="-$(pwgen -s 8 1)"
  - export ADMIN_PASSWORD=$(pwgen -s 16 1)
  - export SEED_JOB_GROOVY_FILE=jenkins/pipeline-configure.groovy
  - make deploy test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    make jenkins-aws; fi

after_script:
  - make cleanup
