language: go
os: linux
arch: arm64-graviton2

sudo: required

addons:
  apt:
    update: true

go:
  - 1.14.x

env:
  global:
    - GO111MODULE=off
    - secure: KMIVfg0F8qAOy1nqTKbuoaRspkDTPUmwsFYvuOT5mfCJxyE7BrVUB/fqnV9RX7eHBzRX4GnfMxDRflGpAvOXypXIxRICfWtjIVRuq4iqeBQDuf+DH61Modp7bFU48CHTw6mAlFh+FYfI6KgPRTnaQu8g3bs/u12qBqI6HWzUV9mRVnUegoau0mwJbUrS6Xu+qiNkKt6h0ITb2a6v9WIBKL0Lf9azVKAC2Rjm/ITD0N+rki+uvTGAtLZ9FXaeqmVcuMecPnrrduA4TpZMWmXypQ6fJOKrmfdgMhAnLXxbnufL5f+GYwcmb3JMnraYZOPK6uHiFnoR/C8LcUr9PNcz8eSnQTb+pSalJFLVvCeDJneEdOt/AWWk6B9ycy+7r3w7W6+Nd9o8O2njqzDXgP+SfuGmiWLLdW2jynL/v9Z2Eo+1iQ54O7pGSO78qdKuEteJB3oNQDCJirbGsf1onDTfxiGp8TbB92Y6iyFN3VQWtfj/Ucdp3uPpB13FIMG+NgyuZOZc3drMUGrtb9FymhqjgiayDSuExVpvGckhcmSbPbUPu1EoIarJGHQIzB2ocxxQb9yptpOpIWrp0XI9LPqsuFdQ5VdI3PU7r0AswAd6LoVZ8wMM/SxTOncTLWK8CMGZMP3ZNkJeKVFNiJkdj5CQTSydsV40vxeOeYYA/MTrFj8=
    - secure: uvSguQCAqU77ZlvmRtWj3asKKCXNf0paa6DlFIujdsC7M2WH46qSxpIp0RqIOkE3a+t4uKx7avGLP4CE84csbszp+sZgknN+UHOtLbkRYT3N8S+NOJZHODmBvdZ92vImcp3qgDap/mn1g1TZmxeNvMqatmAmrawemH8LHiRLZ26wGu7J1acpRQOARdvdjaP2xRPxFbF7LZwN8zzLld82rPwRHpm7Ol4uVr15xahxeSnEsDHa37ESbf+lL9jNWu+yvUBdN50RLxax/eTb8aYvmR74mqHuqOCGkSAxf3RNEIg8tRlIPALsDdrTplqhHGHTzLuI7JWDAtNDY71VvYjBSonZhFXa+zIN85xwzhtdpiAt1W0u3CkbDWolytP7FbNYIxL6jO/I71WZ473HezJWhvRs+y/uP4ux+SPcfFtA81ljuqRyc+Yv+mEQleI0l2hOUNiok1HJal3wB+5Ix60OnzVdj3/qR+kXJMpQjy1q2MPXpPTwZ6tvkOK36Tj4Yd7ecZ5V175Iynr0cUdx9c3hpxRAcGQzktwi4BEVt52puJA6u9GX1s1blZxAbscu8rwNdRKWKYa8jYapPBgQgyQyPtNScWeG05TlELgjolsOTrs4H8i3+X7BJLXCcXzb39UZpAm5c3UeAWE4Iw9nK2swTa6rXJlGlh2ijSOe5KD9PuA=

before_install:
  - curl -fsSL https://get.pulumi.com/ | sh
  - export PATH=$PATH:$HOME/.pulumi/bin
  - pulumi version
  - sudo apt-get -y install pwgen #used in Makefile to generate the random admin password

script:
  - export STACK_SUFFIX="-$(pwgen -s 8 1)"
  - export ADMIN_PASSWORD=$(pwgen -s 16 1)
  - export SEED_JOB_GROOVY_FILE=jenkins/pipeline-configure.groovy
  - make deploy test

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then
    make jenkins-aws; fi

after_script:
  - make cleanup
