#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: false

manage-resolv-conf: true
resolv_conf:
  nameservers:
  - '8.8.8.8'
  - '8.8.4.4'

packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common

write_files:
- path: /etc/systemd/system/jocker.service.env
  permissions: 0644
  owner: root
  content: |
    {{ ADMIN_PASSWORD }}

- path: /etc/systemd/system/jocker.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Run an jocker container
    Author=Frank Ittermann
    Requires=docker.service
    After=docker.service

    [Service]
    Restart=always
    ExecStartPre=-/usr/bin/docker rm jocker
    ExecStart=/usr/bin/docker run --rm -p 80:8080 --env-file /etc/systemd/system/jocker.service.env --name jocker fr123k/jocker
    ExecStop=/usr/bin/docker stop -t 2 jocker

runcmd:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
- add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- apt-get update -y
- apt-get install -y docker-ce docker-ce-cli containerd.io
- systemctl start docker
- systemctl enable docker
- systemctl daemon-reload
- systemctl start jocker.service
