node ("docker-1") {
    stage('Checkout') {
        cleanWs()
        checkout scm
    }
    stage('Debug') {
        sh("bash --version")
        sh("make --version")
        sh("go version")
        sh("pulumi version")
        sh("pwgen")
        sh("make local")
    }
}
