node ("pulumi") {
    stage('Checkout') {
        cleanWs()
        checkout scm
    }
    stage('Debug') {
        sh("bash --version")
        sh("make --version")
        sh("go version")
        sh("pulumi version")
        sh("pwgen")
        withCredentials([usernamePassword(credentialsId: 'aws-key-credentials', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
            try {
                withEnv(['SEED_JOB_GROOVY_FILE=jenkins/pipeline-job.groovy']) {
                    sh("printenv | sort")
                    sh("make local")
                }
            } catch(err) {
                currentBuild.result = 'UNSTABLE'
                sh("make cleanup")
                throw(err)
            }
        }
    }
}
