node ("docker-1") {
    stage('Checkout') {
        cleanWs()
        checkout scm
    }
    stage('Debug') {
        sh("bash --version")
        sh("make --version")
        sh("go version")
        sh("pulumi version")
        sh("pwgen")
        withCredentials([usernamePassword(credentialsId: 'aws-key-credentials', passwordVariable: 'AWS_SECRET_ACCESS_KEY', usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
            sh("make local")
        }
    }
}
