---
jenkins:
  nodes:
    ########
    # Docker Agent for Docker Daemon
    ########
    - permanent:
        name: "docker-1"
        labelString: "docker"
        nodeName: "docker-1"
        remoteFS: "docker-1"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false

unclassified:
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
  ##########
  # job agents on demand
  ##########
  jobNodesOnDemandConfiguration:
    enabled: true
    revision: "origin/master"
    gitUrl: "https://github.com/fr123k/jocker-agents"
    gitRevision: "origin/master"
    excludeLabels: docker
    agentProvisionJob: "jenkins/DockerAgentBootstrap"
    agentDecomissionJob: "jenkins/DockerAgentDestroy"
    agentImage: "fr123k/jocker-agents-{label}"
    agentWorkDir: "/home/jenkins"
  globalDefaultFlowDurabilityLevel:
    durabilityHint: "PERFORMANCE_OPTIMIZED"
  ##########
  # Priority Sorter Plugin
  ##########
  prioritySorterConfiguration:
    strategy:
      absoluteStrategy:
        defaultPriority: 3
        numberOfPriorities: 5
  priorityConfiguration:
    jobGroups:
      - id: 0
        priority: 1
        description: "Jenkins"
        runExclusive: false
        usePriorityStrategies: true
        priorityStrategies:
          - userIdCauseStrategy:
              priority: 1
          - upstreamCauseStrategy
          - userIdCauseStrategy:
              priority: 3
          - cLICauseStrategy:
              priority: 4
          - jobPropertyStrategy
          - buildParameterStrategy:
              parameterName: priority
        jobGroupStrategy:
          folderBased:
            folderName: "Jenkins"
      - id: 0
        priority: 2
        description: "Else"
        runExclusive: false
        usePriorityStrategies: false
        jobGroupStrategy: allJobs
