---
jenkins:
  nodes:
    ########
    # Docker Agent for Docker Daemon
    ########
    - permanent:
        name: "docker-1"
        labelString: "docker"
        nodeName: "docker-1"
        remoteFS: "docker-1"
        numExecutors: 2
        launcher:
          jnlp:
            workDirSettings:
              failIfWorkDirIsMissing: false

unclassified:
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
  ##########
  # job agents on demand
  ##########
  jobNodesOnDemandConfiguration:
    enabled: true
    revision: "origin/master"
    gitUrl: "https://github.com/fr123k/jocker-agents"
    gitRevision: "origin/master"
    excludeLabels: docker
    agentProvisionJob: "jenkins/DockerAgentBootstrap"
    agentDecomissionJob: "jenkins/DockerAgentDestroy"
    agentImage: "fr123k/jocker-agents-{label}"
    agentWorkDir: "/home/jenkins"
  globalDefaultFlowDurabilityLevel:
    durabilityHint: "PERFORMANCE_OPTIMIZED"
